### ISSUE TITLE
List-value separator is ignored on columns with valueUrl

### ISSUE THREAD

**Issue by bencomp** [ruby-rdf/rdf-tabular#10]
When I specify that a column is separated by `;` and the column has a `valueUrl` template too, validation of foreign key constraints fails even though each of the values in the list are in the referenced column. When there is a `valueUrl` specification, the separator is ignored and the referenced column is searched for `value1;value2` – which is not in the list.

The column definition:
```json
{
  "name": "type",
  "titles": ["type"],
  "separator": ";",
  "datatype": "string",
  "propertyUrl": "rdf:type",
  "valueUrl": "https://example.org/ns/class/{type}"
}
```

The CSV value: `service;software`.

Command and stacktrace:
```sh
% rdf serialize --input-format tabular --metadata csv-metadata.json --no-prov \
 --output-format turtle --validate --minimal
ERROR   Table file:things.csv row 202(src 203): Foreign Key violation, expected to find ["service;software"]
Traceback (most recent call last):
        15: from /usr/local/lib/ruby/gems/2.7.0/bin/rdf:23:in `<main>'
        14: from /usr/local/lib/ruby/gems/2.7.0/bin/rdf:23:in `load'
        13: from /usr/local/lib/ruby/gems/2.7.0/gems/rdf-3.1.12/bin/rdf:13:in `<top (required)>'
        12: from /usr/local/lib/ruby/gems/2.7.0/gems/rdf-3.1.12/lib/rdf/cli.rb:537:in `exec'
        11: from /usr/local/lib/ruby/gems/2.7.0/gems/rdf-3.1.12/lib/rdf/cli.rb:676:in `parse'
        10: from /usr/local/lib/ruby/gems/2.7.0/gems/rdf-3.1.12/lib/rdf/cli.rb:676:in `new'
         9: from /usr/local/lib/ruby/gems/2.7.0/gems/rdf-tabular-3.1.1/lib/rdf/tabular/reader.rb:76:in `initialize'
         8: from /usr/local/lib/ruby/gems/2.7.0/gems/rdf-3.1.12/lib/rdf/reader.rb:319:in `initialize'
         7: from /usr/local/lib/ruby/gems/2.7.0/gems/rdf-3.1.12/lib/rdf/reader.rb:319:in `instance_eval'
         6: from /usr/local/lib/ruby/gems/2.7.0/gems/rdf-tabular-3.1.1/lib/rdf/tabular/reader.rb:97:in `block in initialize'
         5: from /usr/local/lib/ruby/gems/2.7.0/gems/rdf-3.1.12/lib/rdf/util/logger.rb:195:in `log_depth'
         4: from /usr/local/lib/ruby/gems/2.7.0/gems/rdf-3.1.12/lib/rdf/util/logger.rb:261:in `log_depth'
         3: from /usr/local/lib/ruby/gems/2.7.0/gems/rdf-tabular-3.1.1/lib/rdf/tabular/reader.rb:156:in `block (2 levels) in initialize'
         2: from /usr/local/lib/ruby/gems/2.7.0/gems/rdf-3.1.12/lib/rdf/cli.rb:677:in `block in parse'
         1: from /usr/local/lib/ruby/gems/2.7.0/gems/rdf-3.1.12/lib/rdf/cli.rb:538:in `block in exec'
/usr/local/lib/ruby/gems/2.7.0/gems/rdf-tabular-3.1.1/lib/rdf/tabular/reader.rb:265:in `each_statement': Errors found during processing (RDF::ReaderError)
        15: from /usr/local/lib/ruby/gems/2.7.0/bin/rdf:23:in `<main>'
        14: from /usr/local/lib/ruby/gems/2.7.0/bin/rdf:23:in `load'
        13: from /usr/local/lib/ruby/gems/2.7.0/gems/rdf-3.1.12/bin/rdf:13:in `<top (required)>'
        12: from /usr/local/lib/ruby/gems/2.7.0/gems/rdf-3.1.12/lib/rdf/cli.rb:537:in `exec'
        11: from /usr/local/lib/ruby/gems/2.7.0/gems/rdf-3.1.12/lib/rdf/cli.rb:676:in `parse'
        10: from /usr/local/lib/ruby/gems/2.7.0/gems/rdf-3.1.12/lib/rdf/cli.rb:676:in `new'
         9: from /usr/local/lib/ruby/gems/2.7.0/gems/rdf-tabular-3.1.1/lib/rdf/tabular/reader.rb:76:in `initialize'
         8: from /usr/local/lib/ruby/gems/2.7.0/gems/rdf-3.1.12/lib/rdf/reader.rb:319:in `initialize'
         7: from /usr/local/lib/ruby/gems/2.7.0/gems/rdf-3.1.12/lib/rdf/reader.rb:319:in `instance_eval'
         6: from /usr/local/lib/ruby/gems/2.7.0/gems/rdf-tabular-3.1.1/lib/rdf/tabular/reader.rb:97:in `block in initialize'
         5: from /usr/local/lib/ruby/gems/2.7.0/gems/rdf-3.1.12/lib/rdf/util/logger.rb:195:in `log_depth'
         4: from /usr/local/lib/ruby/gems/2.7.0/gems/rdf-3.1.12/lib/rdf/util/logger.rb:261:in `log_depth'
         3: from /usr/local/lib/ruby/gems/2.7.0/gems/rdf-tabular-3.1.1/lib/rdf/tabular/reader.rb:156:in `block (2 levels) in initialize'
         2: from /usr/local/lib/ruby/gems/2.7.0/gems/rdf-3.1.12/lib/rdf/cli.rb:677:in `block in parse'
         1: from /usr/local/lib/ruby/gems/2.7.0/gems/rdf-3.1.12/lib/rdf/cli.rb:538:in `block in exec'
/usr/local/lib/ruby/gems/2.7.0/gems/rdf-tabular-3.1.1/lib/rdf/tabular/reader.rb:265:in `each_statement': Errors found during processing (RDF::ReaderError)
```

When I remove the `valueUrl` property from the csv-metadata, validation succeeds and in RDF I get:
```turtle
<thing> a "software",
    "service".
```

When I don't validate, conversion to RDF also succeeds:
```turtle
<thing> a <https://example.org/ns/class/software,service>.
```

I had hoped that converting the CSV to RDF also expanded each value to its own IRI, but then learned that rdf-tabular correctly creates one IRI with the list of values expanded.

So although I may need to change my data or data model to fit my use case, I do wonder if the validation failure was to be expected. I think each list value should be checked individually to foreign keys, but I am not sure I interpret the Recommendations correctly.

[Tabular Metadata § Schemas](https://www.w3.org/TR/2015/REC-tabular-metadata-20151217/#schemas) suggests a FK reference must reference a single row:
> As defined in [tabular-data-model], validators MUST check that, for each row, the combination of cells in the referencing columns references a unique row within the referenced table through a combination of cells in the referenced columns. For examples, see section 5.5.2.1 Foreign Key Reference Between Tables and section 5.5.2.2 Foreign Key Reference Between Schemas.

[Model for tabular data etc. § Rows](https://www.w3.org/TR/tabular-data-model/#rows) says a row can have multiple referenced rows – one for each foreign key reference:
> referenced rows — a possibly empty list of pairs of a foreign key and a row in a table within the same group of tables (which may be another row in the table in which this row appears).

What do others think?

**Comment by gkellogg** [comment]
> When I specify that a column is separated by `;` and the column has a `valueUrl` template too, validation of foreign key constraints fails even though each of the values in the list are in the referenced column. When there is a `valueUrl` specification, the separator is ignored and the referenced column is searched for `value1;value2` – which is not in the list.
> 
> The column definition:
> 
> ```json
> {
>   "name": "type",
>   "titles": ["type"],
>   "separator": ";",
>   "datatype": "string",
>   "propertyUrl": "rdf:type",
>   "valueUrl": "https://example.org/ns/class/{type}"
> }
> ```
> 
> The CSV value: `service;software`.

It seems reasonable to expect that the foreign key constants would not depend on valueUrl. Both the spec and the code are obscure enough that it's hard to tell if this is intentional. The best bet will be to make it work and see if it breaks any tests, which are fairly comprehensive of corner-cases. I'll put this on my list to do.

> 
> I had hoped that converting the CSV to RDF also expanded each value to its own IRI, but then learned that rdf-tabular correctly creates one IRI with the list of values expanded.

Other's have noted that valueUrl doesn't always do what you want or expect it to do, and that templates could be used for things other than URLs. Something that might be looked at in the future, if there's interest.

> [Tabular Metadata § Schemas](https://www.w3.org/TR/2015/REC-tabular-metadata-20151217/#schemas) suggests a FK reference must reference a single row:
> 
> > As defined in [tabular-data-model], validators MUST check that, for each row, the combination of cells in the referencing columns references a unique row within the referenced table through a combination of cells in the referenced columns. For examples, see section 5.5.2.1 Foreign Key Reference Between Tables and section 5.5.2.2 Foreign Key Reference Between Schemas.
> 
> [Model for tabular data etc. § Rows](https://www.w3.org/TR/tabular-data-model/#rows) says a row can have multiple referenced rows – one for each foreign key reference:
> 
> > referenced rows — a possibly empty list of pairs of a foreign key and a row in a table within the same group of tables (which may be another row in the table in which this row appears).

Note that the Rows model is somewhat abstract, as the metadata deals in columns. Logically speaking,, there is a row model as well, although not really manifest directly within the metadata.

Because foreign keys may be made from multiple columns, a single composite foreign key will reference a unique row. But, a row could have multiple foreign key constraints, each of which is composite (possibly including overlapping columns). Thus a row can have multiple referenced rows pairs.

**Comment by gkellogg** [comment]
Upon further investigation, this is falling afoul of general issues on the use of `valueUrl` and `separator`. According to [Tabular Data Model Section 6.4 "Parsing Cells"](https://www.w3.org/TR/2015/REC-tabular-data-model-20151217/#parsing-cells), the use of `separator` is really for those columns with a `datatype`. The `valueUrl` case is treated separately and acts on the `cell`, not the `cell value`, which would have a `list` annotation.

So the foreign key relationship is not held, as using `valueUrl` treats "service;software" as a single value, transformed to the URL "https://example.org/ns/class/service,software", not two separate urls "https://example.org/ns/class/service" and "https://example.org/ns/class/software", as you might expect. This is because [URI Template](https://tools.ietf.org/html/rfc6570) has particular logic for dealing with multiple values as defined in [Section 3.2.1](https://tools.ietf.org/html/rfc6570#section-3.2.1):

> For a variable that is a list of values, expansion depends on both
   the expression type and the presence of an explode modifier.  If
   there is no explode modifier, the expansion consists of a comma-
   separated concatenation of the defined member string values.  If
   there is an explode modifier and the expression type expands named
   parameters (";", "?", or "&"), then the list is expanded as if it
   were an associative array in which each member value is paired with
   the list's varname.  Otherwise, the value will be expanded as if it
   were a list of separate variable values, each value separated by the
   expression type's associated separator as defined by the table above.

Even though you might validate the foreign key relationships of each cell value, it seems that your intent is to actually result in multiple URLs and statements, and the spec doesn't allow for that. You might consider adding a feature request at https://github.com/w3c/csvw/issues to support such a feature, but I think it would need additional metadata to describe the desired behavior so as not to create a backwards compatibility issue.
